### ISSUE TITLE
add -version command

### ISSUE THREAD

**Issue by osteensco** [osteensco/fastTravelCLI#15]
Add a command the displays current version.
should be called like
```bash
ft -version
# or
ft -v
```

maybe also display the fastTravelCLI ascii art
```
     __           _  _____                     _   ___   __   _____ - -  -  -   -   -
    / _| ____ ___| |/__   \___  ______   _____| | / __\ / /   \_   \ - -  -  -   -   -
   | |_ / _  / __| __|/ /\/  _\/ _  \ \ / / _ \ |/ /   / /     / /\/  - -  -   -   -
   |  _| (_| \__ \ |_/ /  | | | (_| |\ V /  __/ / /___/ /___/\/ /_  - -  -  -   -   -
   |_|  \__._|___/\__\/   |_|  \__._| \_/ \___|_\____/\____/\____/ - -  -  -   -   -
                                                                    
version 0.1.1
```

**Comment by anveshthakur** [comment]
Hi @osteensco, 

Great repository, I wanted to ask from where should I fetch that version name?

**Comment by osteensco** [comment]
Thanks! Not sure if there is a way to get it through the GitHub API or if it would need to be hard coded. I'm purposefully leaving it open ended since I haven't looked into the best way to do it.
