### ISSUE TITLE
add ? command

### ISSUE THREAD

**Issue by osteensco** [osteensco/fastTravelCLI#18]
add a command that asks fastTravelCLI if the current working dir is a key thats saved
```
ft ?
```

**Comment by anveshthakur** [comment]
hi @osteensco, do you think we can use something like this for this feature?
https://github.com/vishalkuo/bimap

**Comment by osteensco** [comment]
We wouldn't need an additional tool, this should be just a simple look up in fastTravel's map.

**Comment by anveshthakur** [comment]
got your point @osteensco , I just wanted to avoid a linear search and wanted to implement it with a bidirectional map if you think it is not required I'll just go ahead and implement it?

**Comment by osteensco** [comment]
I dont think its really necessary right now, I imagine most use cases of fastTravel would have less than 50 keys. If fastTravel picks up users and it surfaces as a problem for some then I'd revisit implementing a bidirectional map at that point.

**Comment by anveshthakur** [comment]
Makes sense @osteensco , I'll work on it and raise a MR.

Thanks!

**Comment by anveshthakur** [comment]
hi @osteensco, There is a slight issue with this zsh considers ? as a wildcard to match any single character in filenames.
so we either have to escape it like ```ft \? ``` in zsh or we have to come up with a new command for this

**Comment by anveshthakur** [comment]
I think the shorter the better, -is should be fine.
